config/routes.rb
Rails.application.routes.draw do
  resources :avaliacaos
  resources :atividades
  resources :alunos
  resources :disciplinas
  resources :turmas
  resources :users
  root 'welcome#home'

  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy"
end

app/models/turma.rb
class Turma < ApplicationRecord
  has_many :disciplinas, dependent: :destroy
  has_many :turmas, dependent: :destroy
  validates :letra, presence: true, length: {is:1}, format: { with: /\A[a-zA-Z]+\z/, message: "Somente uma letra"}
  validates :anoLetivo, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 2020, message: "Ano letivo a partir de 2020" }
  validates :ano, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 9, message: "Ano (serie) de 1º a 9º" }
end

app/controllers/turmas_controller.rb
class TurmasController < ApplicationController
  before_action :set_turma, only: %i[ show edit update destroy ]
  before_action :authorized, only: %i[ index show new edit create update destroy]

  # GET /turmas or /turmas.json
  def index
    @turmas = Turma.all
  end

  # GET /turmas/1 or /turmas/1.json
  def show
  end

  # GET /turmas/new
  def new
    @turma = Turma.new
  end

  # GET /turmas/1/edit
  def edit
  end

  # POST /turmas or /turmas.json
  def create
    @turma = Turma.new(turma_params)

    respond_to do |format|
      if @turma.save
        format.html { redirect_to @turma, notice: "Turma was successfully created." }
        format.json { render :show, status: :created, location: @turma }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @turma.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turmas/1 or /turmas/1.json
  def update
    respond_to do |format|
      if @turma.update(turma_params)
        format.html { redirect_to @turma, notice: "Turma was successfully updated." }
        format.json { render :show, status: :ok, location: @turma }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @turma.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turmas/1 or /turmas/1.json
  def destroy
    @turma.destroy
    respond_to do |format|
      format.html { redirect_to turmas_url, notice: "Turma was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turma
      @turma = Turma.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def turma_params
      params.require(:turma).permit(:letra, :anoLetivo, :ano)
    end
end

app/helpers/turmas_helper.rb
module TurmasHelper
end

app/views/turmas/_form.html.erb
<%= form_with(model: turma) do |form| %>
  <% if turma.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(turma.errors.count, "error") %> prohibited this turma from being saved:</h2>

      <ul>
        <% turma.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :letra %>
    <%= form.text_field :letra %>
  </div>

  <div class="field">
    <%= form.label :anoLetivo %>
    <%= form.number_field :anoLetivo %>
  </div>

  <div class="field">
    <%= form.label :ano %>
    <%= form.number_field :ano %>
  </div>

  <div class="actions">
    <%= form.submit value='submit' %>
  </div>
<% end %>

app/views/turmas/edit.html.erb
<h1>Editing Turma</h1>

<%= render 'form', turma: @turma %>

<%= link_to 'Show', @turma %> |
<%= link_to 'Back', turmas_path %>

app/views/turmas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Turmas</h1>

<table>
  <thead>
    <tr>
      <th>Letra</th>
      <th>Anoletivo</th>
      <th>Ano</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @turmas.each do |turma| %>
      <tr>
        <td><%= turma.letra %></td>
        <td><%= turma.anoLetivo %></td>
        <td><%= turma.ano %></td>
        <td><%= link_to 'Show', turma %></td>
        <td><%= link_to 'Edit', edit_turma_path(turma) %></td>
        <td><%= link_to 'Destroy', turma, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Turma', new_turma_path %>

app/views/turmas/new.html.erb
<h1>New Turma</h1>

<%= render 'form', turma: @turma %>

<%= link_to 'Back', turmas_path %>

app/views/turmas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Anoletivo:</strong>
  <%= @turma.anoLetivo %>
</p>

<p>
  <strong>Turma:</strong>
  <%= @turma.letra %>
</p>

<p>
  <strong>Ano:</strong>
  <%= @turma.ano %>
</p>

<p>
  <strong>Disciplinas: </strong>
<table>
  <thead>
  <tr>
    <th>Nome</th>
    <th>Ano Letivo</th>
  </tr>
  </thead>

  <tbody>
  <% @turma.disciplinas.each do |disciplina| %>
    <tr>
      <td><%= disciplina.nome %></td>
      <td><%= disciplina.anoLetivo %></td>
      <td><%= link_to 'Ver Disciplina', disciplina %></td>
    </tr>
  <% end %>
  </tbody>
</table>
</p>

<%= link_to 'Edit', edit_turma_path(@turma) %> |
<%= link_to 'Back', turmas_path %>