config/routes.rb
Rails.application.routes.draw do
  resources :avaliacaos
  resources :atividades
  resources :alunos
  resources :disciplinas
  resources :turmas
  resources :users
  root 'welcome#home'

  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy"
end

app/models/avaliacao.rb
class Avaliacao < ApplicationRecord
  belongs_to :atividade
  belongs_to :aluno

  validates :pontos,
            presence: true,
            numericality: {
              only_integer: true,
              greater_than_or_equal_to: 0,
              less_than_or_equal_to: 10,
              message: "Pontuação de 0 até 10" }
  validates :observacoes,
            length: {
              minimum: 0,
              maximum: 100,
              message: "Observações com no máximo 100 caracteres"}
  validates :atividade_id, presence: true
  validates :aluno_id, presence: true

  def user_id
    @user_id = atividade.user_id
  end
end

app/controllers/avaliacaos_controller.rb
class AvaliacaosController < ApplicationController
  before_action :set_avaliacao, only: %i[ show edit update destroy ]
  before_action :set_atividades, only: %i[ new create edit update ]
  before_action :set_alunos, only: %i[ new create edit update ]
  before_action :authorized, only: %i[ index show new edit create update destroy]

  # GET /avaliacaos or /avaliacaos.json
  def index
    @avaliacaos = Avaliacao.all
  end

  # GET /avaliacaos/1 or /avaliacaos/1.json
  def show
  end

  # GET /avaliacaos/new
  def new
    @avaliacao = Avaliacao.new
  end

  # GET /avaliacaos/1/edit
  def edit
  end

  # POST /avaliacaos or /avaliacaos.json
  def create
    @avaliacao = Avaliacao.new(avaliacao_params)

    respond_to do |format|
      if @avaliacao.save
        format.html { redirect_to @avaliacao, notice: "Avaliacao was successfully created." }
        format.json { render :show, status: :created, location: @avaliacao }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @avaliacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /avaliacaos/1 or /avaliacaos/1.json
  def update
    respond_to do |format|
      if @avaliacao.update(avaliacao_params)
        format.html { redirect_to @avaliacao, notice: "Avaliacao was successfully updated." }
        format.json { render :show, status: :ok, location: @avaliacao }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @avaliacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /avaliacaos/1 or /avaliacaos/1.json
  def destroy
    @avaliacao.destroy
    respond_to do |format|
      format.html { redirect_to avaliacaos_url, notice: "Avaliacao was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_avaliacao
      @avaliacao = []
      avaliacao = Avaliacao.find(params[:id])
      if avaliacao.user_id == current_user.id
        @avaliacao = avaliacao
      else
        redirect_to avaliacaos_path
      end
    end

    def set_atividades
      @atividades = []
      #current_user.disciplinas.each do |disciplina|
      #  @atividades << disciplina.atividades
      #end
      atividades = Atividade.all
      atividades.each do |atividade|
        if atividade.user_id == current_user.id
          @atividades << atividade
        end
      end

      @atividades = @atividades.map{ |ativ| [ativ.titulo.to_s + "-" + ativ.bimestre.to_s, ativ.id]}
    end

    def set_alunos
      @alunos = Aluno.all.map{ |aluno| [aluno.nome.to_s, aluno.id]}
    end

    # Only allow a list of trusted parameters through.
    def avaliacao_params
      params.require(:avaliacao).permit(:pontos, :observacoes, :atividade_id, :aluno_id)
    end
end

app/helpers/avaliacaos_helper.rb
module AvaliacaosHelper
end

app/views/avaliacaos/_form.html.erb
<%= form_with(model: avaliacao) do |form| %>
  <% if avaliacao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(avaliacao.errors.count, "error") %> prohibited this avaliacao from being saved:</h2>

      <ul>
        <% avaliacao.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :pontos %>
    <%= form.number_field :pontos %>
  </div>

  <div class="field">
    <%= form.label :observacoes %>
    <%= form.text_area :observacoes %>
  </div>

  <div class="field">
    <%= form.label :atividade_id %>
    <%= form.select(:atividade_id, options_for_select(@atividades)) %>
  </div>

  <div class="field">
    <%= form.label :aluno_id %>
    <%= form.select(:aluno_id, options_for_select(@alunos)) %>
  </div>

  <div class="actions">
    <%= form.submit value='submit' %>
  </div>
<% end %>

app/views/avaliacaos/edit.html.erb
<h1>Editing Avaliacao</h1>

<%= render 'form', avaliacao: @avaliacao %>

<%= link_to 'Show', @avaliacao %> |
<%= link_to 'Back', avaliacaos_path %>

app/views/avaliacaos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Avaliacaos</h1>

<table>
  <thead>
    <tr>
      <th>Pontos</th>
      <th>Observacoes</th>
      <th>Atividade</th>
      <th>Aluno</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @avaliacaos.each do |avaliacao| %>
      <tr>
        <td><%= avaliacao.pontos %></td>
        <td><%= avaliacao.observacoes %></td>
        <td><%= avaliacao.atividade_id %></td>
        <td><%= avaliacao.aluno_id %></td>
        <td><%= link_to 'Show', avaliacao %></td>
        <td><%= link_to 'Edit', edit_avaliacao_path(avaliacao), id:"e-#{avaliacao.atividade_id}-#{avaliacao.aluno_id}" %></td>
        <td><%= link_to 'Destroy', avaliacao, method: :delete, data: { confirm: 'Are you sure?' }, id:"d-#{avaliacao.atividade_id}-#{avaliacao.aluno_id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Avaliacao', new_avaliacao_path %>

app/views/avaliacaos/new.html.erb
<h1>New Avaliacao</h1>

<%= render 'form', avaliacao: @avaliacao %>

<%= link_to 'Back', avaliacaos_path %>

app/views/avaliacaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pontos:</strong>
  <%= @avaliacao.pontos %>
</p>

<p>
  <strong>Observacoes:</strong>
  <%= @avaliacao.observacoes %>
</p>

<p>
  <strong>Atividade:</strong>
  <%= @avaliacao.atividade_id %>
</p>

<p>
  <strong>Aluno:</strong>
  <%= @avaliacao.aluno_id %>
</p>

<%= link_to 'Edit', edit_avaliacao_path(@avaliacao) %> |
<%= link_to 'Back', avaliacaos_path %>